### ISSUE TITLE
Does not work well in an SSR application

### ISSUE THREAD

**Issue by jakubdonovan** [trash-and-fire/svelte-lightweight-charts#36] opened 2022-06-13 08:46 UTC
> <Chart> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules.

If I restart my dev server, I get the error:
> Cannot use import statement outside a module

and if I then reload the page, no errors appear and the page loads. 

EDIT: I added lightweight-charts and svelte-lightweight-charts to optimizeDeps and it works more often than not but i still sometimes get the error
>svelte-lightweight-charts doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.
Cannot use import statement outside a module`

How do I go about resolving this issue?

**Comment by trash-and-fire** [comment] 2022-06-13 09:29
Please describe your configuration: bundler, node version and package manager. I will try to reproduce this problem. 

My package is not well defined esmodule because it does not contain "type": "module" in package.json and does not use imports with file extensions. But it is easy to run it in sveltekit or bundle via webpack. Maybe I will able to make a workaround for your configuration.

I want to notice that the base package (lightweight-charts) currently does not support SSR at all. It will crash in node environment due to dom api calls (there is a workaround but it also depends on config). This should be fixed in lightweight-chart@4.0.0 but it is still not yet released =(

**Comment by jakubdonovan** [comment] 2022-06-13 09:35
svelte.config.js
`
import adapter from '@sveltejs/adapter-auto';
import preprocess from 'svelte-preprocess';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://github.com/sveltejs/svelte-preprocess
	// for more information about preprocessors
	preprocess: [
		preprocess({
			postcss: true
		})
	],

	kit: {
		adapter: adapter(),
		vits: {
			optimizeDeps: {
				include: ['lightweight-charts', 'svelte-lightweight-charts']
			}
		}
	}
};
export default config;
`

I'm on node v16.15.0, I use npm, and I use the default sveltekit dev server through npm run dev.

**Comment by trash-and-fire** [comment] 2022-06-13 10:46
Ok, I see this warning on my side.

You need to add:
```
		vite: {
			ssr: {
				noExternal: ['lightweight-charts']
			}
		}
```
This will prevent `Cannot use import statement outside a module` and will allow to build SSR bundle.

>svelte-lightweight-charts doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.
Cannot use import statement outside a module`

Unfortunately this one requires some changes to my package. I will try to figure out how I can fix this and release a new version. It looks like a warning not a blocker. If you have any further problems feel free to write me.

**Comment by jakubdonovan** [comment] 2022-06-13 11:50
> ssr: {
> 				noExternal: ['lightweight-charts']
> 			}

This will do for now. Thank you

**Comment by jakubdonovan** [comment] 2022-06-13 11:56
> Ok, I see this warning on my side.
> 
> You need to add:
> 
> ```
> 		vite: {
> 			ssr: {
> 				noExternal: ['lightweight-charts']
> 			}
> 		}
> ```
> 
> This will prevent `Cannot use import statement outside a module` and will allow to build SSR bundle.
> 
> > svelte-lightweight-charts doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.
> > Cannot use import statement outside a module`
> 
> Unfortunately this one requires some changes to my package. I will try to figure out how I can fix this and release a new version. It looks like a warning not a blocker. If you have any further problems feel free to write me.

Unfortunately, adding this to my config did not solve the issue and I still get error `Cannot use import statement outside a module `

**Comment by trash-and-fire** [comment] 2022-06-16 20:24
I've published next beta. Try `npm install svelte-lightweight-charts@next`.

Add to your config:
```
vite: {
	ssr: {
		noExternal: ['svelte-lightweight-charts', 'lightweight-charts']
	}
}
```

This version should run without any warnings and should reserve space for the chart in SRR. This means that there will be no "jumps" when the chart is initialized.

**Comment by jakubdonovan** [comment] 2022-09-09 10:24
> vite: {
> 	ssr: {
> 		noExternal: ['svelte-lightweight-charts', 'lightweight-charts']
> 	}
> }

Hey, the lib doesn't seem to work again after the recent sveltekit api changes. I moved the following into my vite.config.js
```
ssr: {
		noExternal: ['svelte-lightweight-charts']
	}
```
vite.config.js
```
import path from 'path';
import { sveltekit } from '@sveltejs/kit/vite';

/** @type {import('vite').UserConfig} */
const config = {
	plugins: [sveltekit()],

	server: {
		fs: {
			allow: [path.resolve('../../../kit')]
		}
	},
	ssr: {
		noExternal: ['svelte-lightweight-charts']
	}
};

export default config;
```
and I get the following error when trying to run my dev server

> svelte-lightweight-charts doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.
> 17:08:30 [vite-plugin-svelte] /Users/jakubdonovan/Documents/code/shieldprotocol/src/lib/components/app/token/price.svelte:26:11 Empty block
> 17:08:30 [vite-plugin-svelte] /Users/jakubdonovan/Documents/code/shieldprotocol/src/lib/components/app/token/price.svelte:44:10 Empty block
> 17:08:30 [vite-plugin-svelte] /Users/jakubdonovan/Documents/code/shieldprotocol/src/lib/components/app/token/riskMitigationReport.svelte:8:69 RiskMitigationReport has unused export property 'token_distribution_sheet'. If it is for external reference only, please consider using `export const token_distribution_sheet`
> Cannot use import statement outside a module
> /Users/jakubdonovan/Documents/code/shieldprotocol/node_modules/lightweight-charts/dist/lightweight-charts.esm.development.js:7
> import { bindToDevicePixelRatio } from 'fancy-canvas/coordinate-space';
> ^^^^^^
> 
> SyntaxError: Cannot use import statement outside a module
>     at compileFunction (<anonymous>)
>     at Object.compileFunction (node:vm:352:18)
>     at wrapSafe (node:internal/modules/cjs/loader:1033:15)
>     at Module._compile (node:internal/modules/cjs/loader:1069:27)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at Object.<anonymous> (/Users/jakubdonovan/Documents/code/shieldprotocol/node_modules/lightweight-charts/index.js:6:19)

**Comment by trash-and-fire** [comment] 2022-09-09 14:23
Yes, svelte-kit has had many breaking changes and is currently in a very unstable state. You are correct in moving the ssr section to `vite.config.js`.

Try using `svelte-lightweight-charts@next` as described here https://github.com/trash-and-fire/svelte-lightweight-charts#ssr-and-sveltekit.

I'll try it myself with the latest version of svelte-kit when I have time.

**Comment by trash-and-fire** [comment] 2022-09-10 14:17
I fixed dev mode with this config.
```
import { sveltekit } from '@sveltejs/kit/vite';

/** @type {import('vite').UserConfig} */
const config = {
	plugins: [sveltekit()],
	ssr: {
		noExternal: [
			'svelte-lightweight-charts',
			'lightweight-charts',
			'fancy-canvas',
		]
	},
};

export default config;
```

Unfortunately preview/build mode is not working yet. I'm trying to figure out why.

**Comment by trash-and-fire** [comment] 2022-09-10 14:23
Oh, I'm confused with the commands.. Build preview also works.

**Comment by trash-and-fire** [comment] 2022-09-10 14:25
The next version will be 2.0.0 with 4.0.0 charts which should work on server rendering without any extra effort.

**Comment by jakubdonovan** [comment] 2022-09-10 14:36
> 

I added fancy-canvas to my noExternals and got this error

> 500
> Cannot use import statement outside a module
> 
> /Users/jakubdonovan/Documents/code/svelte-lightweight-charts-minimal/node_modules/lightweight-charts/dist/lightweight-charts.esm.development.js:7
> import { bindToDevicePixelRatio } from 'fancy-canvas/coordinate-space';
> ^^^^^^
> 
> SyntaxError: Cannot use import statement outside a module
>     at Object.compileFunction (node:vm:352:18)
>     at wrapSafe (node:internal/modules/cjs/loader:1033:15)
>     at Module._compile (node:internal/modules/cjs/loader:1069:27)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at Object.<anonymous> (/Users/jakubdonovan/Documents/code/svelte-lightweight-charts-minimal/node_modules/lightweight-charts/index.js:6:19)
>     at Module._compile (node:internal/modules/cjs/loader:1105:14)

**Comment by trash-and-fire** [comment] 2022-09-10 14:40
Try removing `.svelte-kit` folder from the root of the project. May be it is kind of cache or something.

**Comment by jakubdonovan** [comment] 2022-09-10 14:42
> Try removing `.svelte-kit` folder from the root of the project. May be it is kind of cache or something.

Did not help. Did you try with my repo?

**Comment by trash-and-fire** [comment] 2022-09-10 14:45
> Did not help. Did you try with my repo?
Yes, I did it with your repo. Note that there is no `kit` field in `vite.config.js`. Are you sure you are copying correctly?

**Comment by jakubdonovan** [comment] 2022-09-10 14:51
> > Did not help. Did you try with my repo?
> 
> Yes, I did it with your repo. Note that there is no `kit` field in `vite.config.js`. Are you sure you are copying correctly?

Did the chart actually render for you? this is what I see
<img width="989" alt="Screenshot 2022-09-10 at 21 50 06" src="https://user-images.githubusercontent.com/16073448/189488721-ec2fea4a-a0ab-43cb-81da-9705bab218c7.png">

**Comment by jakubdonovan** [comment] 2022-09-10 14:53
> > Did not help. Did you try with my repo?
> 
> Yes, I did it with your repo. Note that there is no `kit` field in `vite.config.js`. Are you sure you are copying correctly?

<img width="989" alt="Screenshot 2022-09-10 at 21 50 06" src="https://user-images.githubusercontent.com/16073448/189488833-069ac605-cf8c-4831-9065-88a25fc727b3.png">

**Comment by trash-and-fire** [comment] 2022-09-10 14:53
There is no `priceData` parameter in the series. Must use `data={priceData}`

**Comment by jakubdonovan** [comment] 2022-09-10 14:55
> There is no `priceData` parameter in the series. Must use `data={priceData}`

My bad, it works now. Thanks for your assistance

**Comment by jakubdonovan** [comment] 2022-09-11 08:53
> There is no `priceData` parameter in the series. Must use `data={priceData}`

This is unrelated but I hope that you might be able to help anyway. I'm struggling to get the library to accept my data. Here is a sample of what one candle worth of data looks like:
```
{
  unix: 1662764400000,
  symbol: 'ETH/USD',
  open: 1721,
  high: 1733.4,
  low: 1707.4,
  close: 1719.8,
  'Volume USD': 1767990.344748692,
  'Volume ETH': 1028.02090054
}
```
Upon feeding the data into the chart, I get the error
`TypeError: can't access property "year", t is undefined` and the chart doesn't render. Changing 'unix' to "time" doesn't solve it either. Is there anything I need to do to format this data for it to become usable by lightweight-charts?

**Comment by jakubdonovan** [comment] 2022-09-12 16:46
@trash-and-fire Hey there brother, quick question. How would I access the chart container to add UI elements as seen below? 
https://i.ibb.co/wswzcyf/Screenshot-2022-09-12-at-23-44-19.png
<img width="1290" alt="Screenshot 2022-09-12 at 23 44 19" src="https://user-images.githubusercontent.com/16073448/189710480-4b8acff1-04ca-4e27-b6af-b9baf59e7aa2.png">

**Comment by trash-and-fire** [comment] 2022-09-12 19:38
See an example of a [legend](https://svelte.dev/repl/1b431bf3d75948769855d14c55bbc5f7). This is close to what you want to do.

As for the properties of the container, they are slightly for other situations.

**Comment by jakubdonovan** [comment] 2022-09-12 22:51
> See an example of a [legend](https://svelte.dev/repl/1b431bf3d75948769855d14c55bbc5f7). This is close to what you want to do.
> 
> As for the properties of the container, they are slightly for other situations.

That was really helpful. I now more or less now what to do. I can get the OHLC data with a handleCrosshairMove function, or I can subscribe to crosshair move with  chart.subscribeCrosshairMove which is probably cleaner. Your doc mentions that ref should be used to access the chart instance. Do you have an example showing that?

**Comment by trash-and-fire** [comment] 2022-09-12 23:26
I would recommend using `on:crosshairMove` to subscribe to the crosshair event. This is equivalent to a direct subscription to an instance.

A chart instance reference is also available, but should be used for one-time actions such as taking a screenshot or fitting content.
```
<script>
    let chartApi;
</script>
<Chart width={400} height={300} ref={(ref) => chartApi = ref}/>
<button on:click={() => chartApi.takeScreenshot()}>Take screenshot</button>
<button on:click={() => chartApi.timeScale().fitContent()}>Fit Content</button>
```
In your case, I think the problem is the `CandlestickSeries`. You need to get ref to the series via 
```
<script>
let series;
</script>
<CandlestickSeries ref={(api) => series = api}/>
```
And then you can use `series` in the expression `const price = param.seriesPrices.get(series)`

**Comment by jakubdonovan** [comment] 2022-09-12 23:35
> ref={(api) => series = api}

Thank you, that did it!

**Comment by trash-and-fire** [comment] 2022-09-12 23:38
You can have [many series](https://svelte.dev/repl/8338a68cb00b42fe856dee282d0090e9) on a chart, such as a main series and a moving average series. Therefore, you need to ask the price for a specific instance of the series.

**Comment by jakubdonovan** [comment] 2022-09-13 11:33
> You can have [many series](https://svelte.dev/repl/8338a68cb00b42fe856dee282d0090e9) on a chart, such as a main series and a moving average series. Therefore, you need to ask the price for a specific instance of the series.

I have a question regarding the reactive property. Aassuming that it's the equivalent to `chart.setData()`, I am able to switch to another data set via
```js
function handleIntervalSwitch(interval) {
	seriesOptions.data = data2;
}
```
but the chart position does not reset. The initial data is only a couple candles long do it does not fill the chart container, but the dataset I switch to is, yet it ends where the original does and the chart area does not get filled. How can I fix that?

https://user-images.githubusercontent.com/16073448/189890568-bc38a0f1-37a4-4bd0-891d-61c5439ca624.mp4

**Comment by trash-and-fire** [comment] 2022-09-13 12:30
Could you please provide a minimal reproduction of the issue with reactive data.

Also keep in mind that `data2` must not be equal to `seriesOptions.data`. To be sure, try this:
```
function handleIntervalSwitch(interval) {
	seriesOptions = {
		...seriesOptions,
		data: [...data2],
	}
}
```

**Comment by jakubdonovan** [comment] 2022-09-24 01:08
> Could you please provide a minimal reproduction of the issue with reactive data.
> 
> Also keep in mind that `data2` must not be equal to `seriesOptions.data`. To be sure, try this:
> 
> ```
> function handleIntervalSwitch(interval) {
> 	seriesOptions = {
> 		...seriesOptions,
> 		data: [...data2],
> 	}
> }
> ```
> 
> or just this:
> 
> ```
> function handleIntervalSwitch(interval) {
> 	seriesOptions.data = [...data2];
> }
> ```
> 
> I have a [demo](https://svelte.dev/repl/0efb2840a9844ed5a1d84f2a1c9a2269) where data is reactive.

Hey again, I used your lib to create a sparkline with coingecko data and I'm experiencing a bug I'm not quite sure how to tackle. I have 3 items, and for each item, I render a card with its own sparkline, as it should. But the problem is that more often than not, only the first one will render and the others will not until I switch to another route and then switch back. And then if I do it again, they will disappear again. 

https://user-images.githubusercontent.com/16073448/192073731-0f6b0cbc-301e-4b09-829a-ac1084d90e52.mp4


Here is a minimal reproduction repo:
https://github.com/jakubdonovan/svelte-lightweight-charts-minimal/tree/coingecko-sparkline

**Comment by jakubdonovan** [comment] 2022-09-25 12:18
> Could you please provide a minimal reproduction of the issue with reactive data.
> 
> Also keep in mind that `data2` must not be equal to `seriesOptions.data`. To be sure, try this:
> 
> ```
> function handleIntervalSwitch(interval) {
> 	seriesOptions = {
> 		...seriesOptions,
> 		data: [...data2],
> 	}
> }
> ```
> 
> or just this:
> 
> ```
> function handleIntervalSwitch(interval) {
> 	seriesOptions.data = [...data2];
> }
> ```
> 
> I have a [demo](https://svelte.dev/repl/0efb2840a9844ed5a1d84f2a1c9a2269) where data is reactive.

Just replying again in case you didn't see my earlier comment

**Comment by trash-and-fire** [comment] 2022-09-25 13:16
Please mock your data. Don't really want to go to unknown hosts.

Check this line https://github.com/jakubdonovan/svelte-lightweight-charts-minimal/blob/coingecko-sparkline/src/lib/stores/tokens.js#L14 please. It looks like you never add new keys to an object.

**Comment by matthewwwz** [comment] 2022-10-21 16:09
> Следующая версия будет 2.0.0 с диаграммами 4.0.0, которые должны работать на серверном рендеринге без каких-либо дополнительных усилий.

Do you have any information about the release date of 4.0 lightweight chart?

**Comment by matthewwwz** [comment] 2022-10-21 16:10
> The next version will be 2.0.0 with 4.0.0 charts which should work on server rendering without any extra effort.

Do you have any information about the release date of 4.0 lightweight chart?

**Comment by trash-and-fire** [comment] 2022-10-21 18:21
I don't have this information. I hope it will happen this year. Support for 4.0 does not require much effort on my part and I will release a new version on the same day.

**Comment by Swoorup** [comment] 2022-11-09 08:04
> I fixed dev mode with this config.
> 
> ```
> import { sveltekit } from '@sveltejs/kit/vite';
> 
> /** @type {import('vite').UserConfig} */
> const config = {
> 	plugins: [sveltekit()],
> 	ssr: {
> 		noExternal: [
> 			'svelte-lightweight-charts',
> 			'lightweight-charts',
> 			'fancy-canvas',
> 		]
> 	},
> };
> 
> export default config;
> ```
> 
> Unfortunately preview/build mode is not working yet. I'm trying to figure out why.

Looks like this no longer works due to upstream changes. But I am also unable to find a replacement for it :/

**Comment by trash-and-fire** [comment] 2022-11-10 15:43
@Swoorup

It still works for me with the following versions:
```
├── @sveltejs/adapter-auto@1.0.0-next.87
├── @sveltejs/kit@1.0.0-next.539
├── autoprefixer@10.4.13
├── eslint-config-prettier@8.5.0
├── eslint-plugin-svelte3@4.0.0
├── eslint@8.27.0
├── lightweight-charts@3.8.0
├── postcss-load-config@4.0.1
├── postcss@8.4.18
├── prettier-plugin-svelte@2.8.0
├── prettier@2.7.1
├── svelte-check@2.9.2
├── svelte-lightweight-charts@1.7.0-next.0
├── svelte-preprocess@4.10.7
├── svelte@3.53.1
├── tailwindcss@3.2.3
├── typescript@4.8.4
└── vite@3.2.3
```
Please provide minimal reproduction, or at least your `npm ls` log.

**Comment by Swoorup** [comment] 2022-11-10 16:50
```
❯ npm ls
├── @improbable-eng/grpc-web@0.15.0
├── @rxjs-ninja/rxjs-utility@5.1.2
├── @sveltejs/adapter-auto@1.0.0-next.87
├── @sveltejs/kit@1.0.0-next.539
├── @sveltestack/svelte-query@1.6.0
├── @svelteuidev/composables@0.7.5
├── @svelteuidev/core@0.7.5
├── @tailwindcss/typography@0.5.8
├── @testing-library/svelte@3.2.2
├── @threlte/core@4.3.3
├── @threlte/extras@4.5.1
├── @types/d3@7.4.0
├── @types/three@0.146.0
├── @typescript-eslint/eslint-plugin@5.42.1
├── @typescript-eslint/parser@5.42.1
├── autoprefixer@10.4.13
├── axios@1.1.3
├── broadcast-channel@4.18.1
├── d3@7.6.1
├── eslint-config-prettier@8.5.0
├── eslint-plugin-svelte3@4.0.0
├── eslint@8.27.0
├── flowbite-svelte@0.27.14
├── flowbite@1.5.3
├── fp-ts-rxjs@0.6.15
├── fp-ts@2.13.1
├── jsdom@20.0.2
├── lightweight-charts@3.8.0
├── postcss-load-config@4.0.1
├── postcss@8.4.18
├── prettier-plugin-svelte@2.8.0
├── prettier@2.7.1
├── rxjs@7.5.7
├── svelte-check@2.9.2
├── svelte-heros@2.3.5
├── svelte-lightweight-charts@1.6.3
├── svelte-preprocess@4.10.7
├── svelte-select@4.4.7
├── svelte@3.53.1
├── tailwindcss@3.2.3
├── three@0.146.0
├── ts-proto@1.131.0
├── tslib@2.4.1
├── typescript@4.8.4
└── vitest@0.25.1
```

```
Unexpected token 'export'
webui/node_modules/fancy-canvas/coordinate-space.js:4
export function bindToDevicePixelRatio(canvas, options) {
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1088:15)
    at Module._compile (node:internal/modules/cjs/loader:1123:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:518:24)

```

**Comment by trash-and-fire** [comment] 2022-11-10 23:26
Try using `npm install svelte-lightweight-charts@next`

**Comment by Swoorup** [comment] 2022-11-11 04:22
> Try using `npm install svelte-lightweight-charts@next`

Still the same issue with `export`. Think this is the PR that resulted in a drastic change to SSR config :/
https://github.com/sveltejs/kit/pull/6197

**Comment by trash-and-fire** [comment] 2022-11-11 07:50
You have the same version of `@svelte/kit` as I do. Try deleting the `.svelte-kit` folder and restart.

**Comment by trash-and-fire** [comment] 2022-11-11 11:26
I don't see vite in your dependencies. What version of vite do you have? Try using `npm install vite@latest`

**Comment by Swoorup** [comment] 2022-11-11 15:32
Tried deleting `.svelte-kit` along with vite@latest install still the same issue.

**Comment by trash-and-fire** [comment] 2022-11-11 19:52
I double checked this. I removed `node_modules` and `.svelte-kit`, ran `npm install`. The result is the same: it still works seamlessly with the latest version of svelte-kit.

Can you provide a demo with the issue?

**Comment by trash-and-fire** [comment] 2023-02-12 22:57
You can use [`svelte-lightweight-charts@2.0.0`](https://github.com/trash-and-fire/svelte-lightweight-charts/releases/tag/2.0.0)

**Closed** 2023-03-12 19:31 UTC
